# Generated by Django 6.0.2 on 2026-03-02 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'permissions': {('viewall_operatingsystem', 'Can view all operating systems')},
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('operating_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', related_query_name='distribution', to='operating_systems.operatingsystem')),
            ],
            options={
                'permissions': {('viewall_distribution', 'Can view all distributions')},
            },
        ),
    ]
